### PR TITLE
Update Astra path definitions

### PR DESCRIPTION
**Pull request by andycasey**
Shortened two keywords in mwmVisit/mwmStar definition because they needed HIERARCH prefixes to be stored in FITS headers, and it drove me crazy:
- `astra_version` -> `v_astra`
- `catalogid` -> `sdss_id`

Added paths for all products from Astra pipelines that generate model spectra. For those that take in mwmStar products:
- astraStarASPCAP
- astraStarCannon
- astraStarKorg
- astraStarPayne
- astraStarPayneChe
- astraStarSLAM
- astraStarWD

And those that take in mwmVisit products:
- astraVisitASPCAP
- astraVisitCannon
- astraVisitKorg
- astraVisitPayne
- astraVisitPayneChe
- astraVisitSLAM
- astraVisitWD

We were going to have these as a generic astraStar/astraVisit definition with a `pipeline` keyword, but we realised that documenting all possible output from each pipeline variant would likely cause confusion.

### CODE REVIEW

**Comment by joelbrownstein** [comment]
Hi @andycasey 

Thanks for opening this discussion.

I am not (overly) opposed to the suggestion: catalogid -> sdss_id
provided this is not an astra only thing.  Who have you 
discusses this with (e.g. @Sean-Morrison @albireox @havok2063)?
We have a glossary in SDSS and under no circumstances can I think of
a situation with both catalogid and sdss_id meaning the same thing.

I am not opposed to the suggestion of a shortened astra_version,
but "v_prod" is unconventional since many sdss paths have
a "prod_ver" (or astra_ver) which is shortish enough(?), and matches
the style better.

**Comment by Sean-Morrison** [comment]
While having an SDSS_id would be useful, since currently, the catalogid is dependent on crossmatch version, I don't think we just want to rename catalogid as sdss_id. Calling it sdss_id would remove visible association to the catalog. If we want to define a sdss_id that was independent of catalog version, that would be something I would support, but this would also need to be consistent across the 3 pipelines. We would also want to produce a new database table that crossmatched these sdss_id to the current and future catalogids.

**Comment by andycasey** [comment]
I thought there'd be way more discussion on having 10 variants of essentially two data models than on the path keywords! I'm gonna leave the decision on this to our data model Czar, @ajwheeler (in other words: "above my pay grade"). Some comments to give context:

I proposed `sdss_id` because there are numerous other identifiers in Astra products and I try to follow the same style of naming, and keep an internal glossary so things are named the same. Similar identifiers are: `gaia_id`, `tic_id`, etc.  An alternative for `catalogid` is `cat_id`, but it seemed less specific than `sdss_id`. Or we just accept `HIERARCH catalogid`.  

`astra_ver` is one character too long (so we'd have `HIERARCH astra_ver`), which is why I proposed `v_astra`. It also matches the style of many version keywords already in place in the BOSS and APOGEE data reduction pipelines (e.g., `V_KAIJU`, `V_BOSS`, `VCOORDIO`).

I'll note though that there are already a lot of inconsistencies between the access paths and data models, and none of them cause any problems. For example:
- `apred` and `run2d` both refer to versions of a code, and neither is `v_<prod>` or `<prod>_ver`. In the `apogeedrp` database tables, `apred` is actually called `apred_vers`.
- Similarly: `fiberid` vs `fiber`.
- I think `obj` in `apStar/apVisit/...` data access paths is the only place it's called `obj`. Everywhere else it is called `APOGEE_ID` (including database tables, FITS files, etc).

As far as I know the only guidelines for naming things are in [this guide](https://sdss-tree.readthedocs.io/en/latest/paths.html).

**Comment by andycasey** [comment]
Also, where's the glossary?

**Comment by joelbrownstein** [comment]
The glossary is being built for SDSS-V, since it was one of the topics at DocuLlama.  You should contact Jordan and Anne-Marie so they can point you to how to start editing wordpress at some point before DR19.  I didn't know about those other V_* optons.  Thanks for pointing that out.  I think you should proceed with your plan to create an 8-char expression for astraver or v_astra as you prefer.  Regarding cat_id; or sdss_id as a short form for catalog_id, I think this can be discussed, as you see fit.

**Comment by ajwheeler** [comment]
It seems sensible to me to avoid "sdss_id" if there's any chance we will want to use it in the future.  "cat_id" is relatively transparent, and we can make it more so by using/defining it in places besides the data model.  It seems like the conservative choice.

I think "v_astra" is the best choice to replace astra _version.

**Comment by joelbrownstein** [comment]
I agree with @ajwheeler on: `v_astra` and the `cat_id` abbreviation.

**Comment by havok2063** [comment]
I also prefer `cat_id` over `sdss_id`, although I'm a bit worried about `cat_id` differing from `catalog_id` when they mean the same thing.   I can understand the use of `v_astra` over `astra_ver` especially if it's necessary for adhering to other specifications.  If it's only one character short, what about `astraver`?  

These are small changes and ok in the end, but they do highlight the continued inconsistency of how we name variables.  The keyword names implicitly carry no context so it's hard for users to know what they mean, to know what values they should take, and it can be quite confusing.   We've never really had naming conventions before, and this has created the problem you highlight.  I took a stab at creating some standards here, https://wiki.sdss.org/display/DATA/DataModel+and+Access+Path+Naming+Conventions+and+Standards, but we could revise this after discussion.  I'd really like to see us move towards some standards as I think they can provide some context for end users plus make it easier for us when defining keywords.  If we want to retain this "wide net" name "flexibility", then we should also consider building in a programmatic/documented lookup, i.e. "these 5 keywords refer to the same concept X".

**Pull request merged**
